PreCommit:
  Prettier:
    enabled: true
    command: ["npx", "prettier", "--check", "."]
  Terraform:
    enabled: true
    command: ["terraform", "fmt"]
    flags: ["-check", "-recursive"]
    install_command: tfenv install
